import { Identity, Tier, WealthLoadout } from "./types";

// Keep in sync with extension/background.js
export const STARTING_NET_WORTH = 120000;

/** Absolute dollar thresholds, per the hackathon spec. */
export function getTier(netWorth: number): Tier {
  if (netWorth >= 100000) return "wealthy";
  if (netWorth >= 10000) return "successful";
  if (netWorth >= 1000) return "average";
  return "poor";
}

export const WEALTH_LOADOUTS: Record<Tier, WealthLoadout> = {
  poor: {
    tier: "poor",
    label: "Homeless",
    blurb: "Cardboard: surprisingly breathable.",
    background: "linear-gradient(180deg, #4b5563, #1f2937)",
    slots: [{ slot: "pants" }, { slot: "shirt" }], // barefoot
  },
  average: {
    tier: "average",
    label: "Getting By",
    blurb: "Rent's paid. Barely.",
    background: "linear-gradient(180deg, #38bdf8, #0ea5e9)",
    slots: [{ slot: "pants" }, { slot: "shoes" }, { slot: "shirt" }],
  },
  successful: {
    tier: "successful",
    label: "Doing Well",
    blurb: "Nice apartment. Maybe a Roth IRA even.",
    background: "linear-gradient(180deg, #a78bfa, #7c3aed)",
    slots: [
      { slot: "pants" },
      { slot: "shoes" },
      { slot: "shirt" },
      { slot: "glasses" },
    ],
    statusItem: "coin",
  },
  wealthy: {
    tier: "wealthy",
    label: "Set for Life",
    blurb: "Compound interest did its thing.",
    background: "linear-gradient(180deg, #facc15, #b45309)",
    slots: [
      { slot: "pants" },
      { slot: "shoes" },
      { slot: "shirt" },
      { slot: "tie", bodies: ["male"] },
      { slot: "jacket", bodies: ["male"] },
      { slot: "necklace" },
      { slot: "glasses" },
    ],
    statusItem: "car",
  },
};

/** Sprite layer paths for an identity at a tier, bottom-to-top. Paths are
 * relative to popup/index.html; files are generated by
 * scripts/fetch_lpc_assets.py into public/sprites/. */
export function layerPaths(identity: Identity, tier: Tier): string[] {
  const loadout = WEALTH_LOADOUTS[tier];
  const layers = [`./sprites/identity/base_${identity.body}_${identity.skin}.png`];
  const garments = loadout.slots
    .filter(({ bodies }) => !bodies || bodies.includes(identity.body))
    .map(({ slot }) => `./sprites/wealth/${tier}/${slot}_${identity.body}.png`);
  // hair sits above garments but below glasses
  const glasses = garments.filter((p) => p.includes("/glasses_"));
  const rest = garments.filter((p) => !p.includes("/glasses_"));
  layers.push(...rest);
  if (identity.hairStyle !== "bald") {
    layers.push(
      `./sprites/identity/hair_${identity.hairStyle}_${identity.hairColor}.png`
    );
  }
  layers.push(...glasses);
  return layers;
}
